### ISSUE TITLE
Ya dood

### ISSUE THREAD

**Issue by BenTearzz** [AurelienLourot/ghuser.io#106]
I'd like to have my profile on ghuser.io, thanks!

**Comment by AurelienLourot** [comment]
here you go :) https://ghuser.io/BenTearzz

you'll probably want to star your projects so they show up on the next refresh (in max. 24 hours), see https://github.com/AurelienLourot/ghuser.io/#some-of-my-repos-are-not-showing-up-on-my-profile-why
