### ISSUE TITLE
Ghuser ftfy!

### ISSUE THREAD

**Issue by anishkny** [AurelienLourot/ghuser.io#115]
I'd like to have my profile on ghuser.io, thanks!

**Comment by AurelienLourot** [comment]
here you go :) https://ghuser.io/anishkny

**Comment by anishkny** [comment]
Thanks! Looks awesome. Will open some enhancement issues soon:

Responsive design
Label for write access
Etc

**Comment by AurelienLourot** [comment]
thanks! there is already an issue for responsive UI: #46 

write access isn't public information, so it's not given by GitHub's API as far as I know

**Comment by jayvdb** [comment]
Write access is roughly covered by https://github.com/AurelienLourot/ghuser.io/issues/97
