### ISSUE TITLE
Hi there!

### ISSUE THREAD

**Issue by SourcingDenis** [AurelienLourot/ghuser.io#119]
I'd like to have my profile on ghuser.io, thanks!

**Comment by AurelienLourot** [comment]
here you go :) https://ghuser.io/SourcingDenis

you probably want to have a look at https://github.com/AurelienLourot/ghuser.io#some-of-my-repos-are-not-showing-up-on-my-profile-why

**Comment by SourcingDenis** [comment]
perfect! thanks 🙌
