### ISSUE TITLE
Profile for nomeata

### ISSUE THREAD

**Issue by nomeata** [AurelienLourot/ghuser.io#138]
I'd like to have my profile on ghuser.io, thanks!

**Comment by AurelienLourot** [comment]
Here you go :) https://ghuser.io/nomeata

Your profile uncovers a new bug: in your company field you point to an organization name containing a dash. I'll look into it later today.

**Comment by AurelienLourot** [comment]
fixed :)

**Comment by nomeata** [comment]
LGTM, thanks! :-)
