### ISSUE TITLE
Profile for philderbeast

### ISSUE THREAD

**Issue by philderbeast** [AurelienLourot/ghuser.io#139]
I'd like to have my profile on ghuser.io, thanks!

**Comment by AurelienLourot** [comment]
here you go :) https://ghuser.io/philderbeast

**Comment by philderbeast** [comment]
Thanks @AurelienLourot. The list of orgs and projects reminds me of contributions I'd made.

**Comment by AurelienLourot** [comment]
you're welcome :)
