### ISSUE TITLE
Do not publicly expose people who tried your service

### ISSUE THREAD

**Issue by giomasce** [AurelienLourot/ghuser.io#152]
I have tried your service and my GitHub handle was publicly exposed in a list of people who subscribed to your service. I personally do not think that publicly distributing lists of your users is a good idea, given that you never received consent for that. Not that I have anything to hide, but I think you can respect others' privacy even when they have nothing to hide.

Please remove my name from there and be more considerate in the future.

As a side note, writing "Hopefully no one will feel spammed" is not enough to make people not feel spammed.

**Comment by AurelienLourot** [comment]
You're right, I didn't see it this way, sorry about that.

**Comment by giomasce** [comment]
If you have a profile, people have to search your specific name to find it out. That is different from creating a list of all of them already collected in one place.

**Comment by ocdtrekkie** [comment]
What's the threat model though? It's a site for making public profiles. If you used it, you wanted a public profile.
