### ISSUE TITLE
Keep the app warm

### ISSUE THREAD

**Issue by AurelienLourot** [AurelienLourot/ghuser.io#2]
We're hosting on AWS Lambda via Up, and often the app gets cold and the next visitor has to wait several seconds to get the page.

We could pay Up to keep it warm: https://up.docs.apex.sh/#configuration.lambda_settings.active_warming

Or we could implement a cheap tool that periodically makes an HTTP GET and runs on our laptops for the prototyping phase.

**Comment by brillout** [comment]
Or one of the many free monitoring tools.

For devarchy I use uptimerobot.com and I'm happy with it so far
