### ISSUE TITLE
Markdown spell checker

### ISSUE THREAD

**Issue by AurelienLourot** [AurelienLourot/ghuser.io#21]
Set up a spell checker like here:
* https://github.com/AurelienLourot/reframe-on-up/blob/master/package.json
* https://github.com/AurelienLourot/reframe-on-up/blob/master/.travis.yml

**Comment by brillout** [comment]
That's really really cool.

Actually I build a little lib https://github.com/brillout/find-package-files that searches all package files.

We could use it with markdown-spellcheck and create a lib that automatically spell checks all markdowns.

In the end it would be enough to do:

```
{
  "scripts": {
    "spellcheck": "spellcheck --ignore-acronyms --no-suggestions --en-us"
  },
  "devDependencies": {
    "@lourot/spellcheck": "^0.1.0"
  }
}
```

**Comment by AurelienLourot** [comment]
@brillout `mdspell` can already search for all `*.md` files and spellcheck them. What would be the added value of our new lib?

**Comment by brillout** [comment]
So you can do `spellcheck` instead of `mdspell '**/*.md' '!**/node_modules/**/*.md'`.

But yea the added value is small. I guess it's not worth it.

**Comment by AurelienLourot** [comment]
🤣 feel free to do it if you feel like it but to me it looks like we would lose, because when we will want to upgrade mdspell, we will have to release a new spellcheck, and then pin that new spellcheck in ghuser. All this just for not writing two arguments 😄

**Comment by brillout** [comment]
You're right^^
