### ISSUE TITLE
HTML title and favicon

### ISSUE THREAD

**Issue by AurelienLourot** [AurelienLourot/ghuser.io#24]

**Comment by hakabuk** [comment]
Happy to do this, if it's up for grabs

**Comment by AurelienLourot** [comment]
Yes please! :)

Setting up your ghuser profile at the moment by the way. And I'll right away extend reframe/README.md to explain how to run a reframe app locally and test your changes, as reframe is not a famous framework (yet!)

**Comment by hakabuk** [comment]
Thanks @AurelienLourot. I was preparing for some trial and error there, so I appreciate the help. I'm in London timezone, so please don't rush it - I can call it a day and start this fresh tomorrow :)
