### ISSUE TITLE
Can I have a profile plz

### ISSUE THREAD

**Issue by manugarri** [AurelienLourot/ghuser.io#40]

**Comment by AurelienLourot** [comment]
Sorry for the delay, I was hit by #50, it should be ready in a few hours hopefully :)

**Comment by AurelienLourot** [comment]
here you go :) https://ghuser.io/manugarri

**Comment by AurelienLourot** [comment]
now hitting #52, working on it, sorry

**Comment by AurelienLourot** [comment]
It looks ok now, thanks for being so patient and for being one of my first users :heart:
https://ghuser.io/manugarri

**Comment by manugarri** [comment]
great, thanks!
