### ISSUE TITLE
Can I also have a profile?

### ISSUE THREAD

**Issue by DiSiqueira** [AurelienLourot/ghuser.io#41]

**Comment by AurelienLourot** [comment]
Sorry I got delayed by #50 and #51. It should be ready in a few hours hopefully :)

**Comment by AurelienLourot** [comment]
here you go :) https://ghuser.io/DiSiqueira

**Comment by DiSiqueira** [comment]
Wow! Thanks a lot @AurelienLourot !! Amazing work!
