### ISSUE TITLE
Could you add mine?

### ISSUE THREAD

**Issue by crazy-max** [AurelienLourot/ghuser.io#42]
Can you add my profile ?
Curious to see the result, thx :)

**Comment by AurelienLourot** [comment]
Sorry I got delayed by #50 and #51. It should be ready in a few hours hopefully :)

**Comment by crazy-max** [comment]
@AurelienLourot Nice thx :)

**Comment by AurelienLourot** [comment]
here you go :) https://ghuser.io/crazy-max

**Comment by AurelienLourot** [comment]
now hitting #52, working on it, sorry

**Comment by AurelienLourot** [comment]
It looks ok now, thanks for being so patient and for being one of my first users :heart:
https://ghuser.io/crazy-max

**Comment by crazy-max** [comment]
Thanks but there is an issue, repo desc and links are are shifted by one, for example :

![image](https://user-images.githubusercontent.com/1951866/42521722-ce1c856c-8469-11e8-9f9b-f6d53b13593e.png)

dokuwiki-plugin-syntaxhighlighter4 = https://github.com/crazy-max/crossfit-reader
git-rewrite-author = https://github.com/crazy-max/dokuwiki-plugin-syntaxhighlighter4
crossfit-reader = https://github.com/crazy-max/dokuwiki-plugin-syntaxhighlighter3

**Comment by AurelienLourot** [comment]
Are you sure? Because it looks good in your screenshot and in my browsers (Chrome and Chromium) it looks the same, and the links are correct.

Could it be that you misinterpret the UI? it is a sequence of such blocks:
```
[logo] title [badges]
       description >
-------------------------
```

and if you click on the description you get

```
[logo] title [badges]
       description v
       [stats]
-------------------------
```

and if you click on the title, it should open the GitHub repo.

If that's the case (UI is unclear), do you know how I could improve the UI to make it more clear? Thanks!

**Comment by AurelienLourot** [comment]
Ah I definitely see something wrong in your screenshot:
* `★ 21` is in a badge, and that shouldn't be the case, and that's correct in my browsers
* `mature` isn't in a badge, although it should, and that's correct in my browsers.

What browser do you have? :)

**Comment by AurelienLourot** [comment]
@crazy-max I was able to reproduce it and now it's fixed for me. For you as well?

**Comment by crazy-max** [comment]
Yes seems fixed :)
