### ISSUE TITLE
Let's see my visualization

### ISSUE THREAD

**Issue by aryaminus** [AurelienLourot/ghuser.io#43]
Interesting UI design

**Comment by AurelienLourot** [comment]
here you go :) https://ghuser.io/aryaminus

**Comment by AurelienLourot** [comment]
now hitting #52, working on it, sorry

**Comment by AurelienLourot** [comment]
It looks ok now, thanks for being so patient and for being one of my first users :heart:
https://ghuser.io/aryaminus
