### ISSUE TITLE
Can I get a profile?

### ISSUE THREAD

**Issue by heyitswither** [AurelienLourot/ghuser.io#44]
By the way, when are you planning on auto generating profiles?

**Comment by AurelienLourot** [comment]
Hi @heyitswither :) 

> Can I get a profile?

Sure, on it :)

> when are you planning on auto generating profiles?

It's going to be a long way there, see https://www.reddit.com/r/coolgithubprojects/comments/8xgebl/ghuserio_better_github_profiles/e23xpm2/

But I intend to improve that process already a bit within about a month, see #49

**Comment by AurelienLourot** [comment]
here you go :) https://ghuser.io/heyitswither

**Comment by AurelienLourot** [comment]
now hitting #52, working on it, sorry

**Comment by AurelienLourot** [comment]
It looks ok now, thanks for being so patient and for being one of my first users :heart:
https://ghuser.io/heyitswither

**Comment by heyitswither** [comment]
Thanks a bunch!
