### ISSUE TITLE
Can I get a profile?

### ISSUE THREAD

**Issue by wilburhimself** [AurelienLourot/ghuser.io#45]

**Comment by AurelienLourot** [comment]
Sorry I got delayed by #50 and #51. It should be ready in a few hours hopefully :)

**Comment by AurelienLourot** [comment]
Here you go :) https://ghuser.io/wilburhimself
Thanks for being so patient and for being one of my first users :heart:

**Comment by wilburhimself** [comment]
Oh thanks, looks gorgeous! I'm about to give back with some contributions. Thanks!
