### ISSUE TITLE
profile request 

### ISSUE THREAD

**Issue by Rupeshiya** [AurelienLourot/ghuser.io#58]
Want to be on ghuser.io

**Comment by AurelienLourot** [comment]
here you go :) https://ghuser.io/Rupeshiya

**Comment by Rupeshiya** [comment]
thanks @AurelienLourot  is it static or dynamic ?

**Comment by AurelienLourot** [comment]
You're welcome :) It's still a baby project, so it's static for now and the data is refreshed at least once per day (if you scroll to the bottom of your profile you can see how old the data is). We wanted to see first if people were interested by such a project. (Thanks for being one of our first users!)

It's under heavy development and will become more and more dynamic.
