### ISSUE TITLE
Request for profile creation

### ISSUE THREAD

**Issue by itaditya** [AurelienLourot/ghuser.io#64]
I'd like to have my profile on ghuser.io, thanks!

**Comment by AurelienLourot** [comment]
here you go :) https://ghuser.io/itaditya

**Comment by itaditya** [comment]
@AurelienLourot can you share your twitter handle, I'd like to mention you and share the awesome work you're doing..

**Comment by AurelienLourot** [comment]
thank you @itaditya :)
https://twitter.com/AurelienLourot
what is yours?

**Comment by itaditya** [comment]
https://twitter.com/dev__adi
