### ISSUE TITLE
Create ghuser profile

### ISSUE THREAD

**Issue by jamesgeorge007** [AurelienLourot/ghuser.io#72]
I'd like to have my profile on ghuser.io, thanks!

**Comment by AurelienLourot** [comment]
on it :)

**Comment by AurelienLourot** [comment]
Here you go :) https://ghuser.io/jamesgeorge007

I see two issues at the first glance:
1. the number of stars (1.5k) should be displayed on the same line as your login
2. the emojis in your bio (`:rocket: :boom: :fire: :+1:`) aren't rendered (I render them only in project descriptions)

I'll fix these issues tomorrow :)

**Comment by AurelienLourot** [comment]
Fixed :) Your profile looks really nice now!
https://ghuser.io/jamesgeorge007
