### ISSUE TITLE
t2.nano too small for `reframe build`?

### ISSUE THREAD

**Issue by AurelienLourot** [AurelienLourot/ghuser.io#73]
We use a [t2.nano EC2 instance](https://github.com/AurelienLourot/ghuser.io/tree/master/aws/ec2) for playing around. `reframe start` works fine but

```
$ npx reframe build --log

Build pages for production.

 ✔ Found project ~/ghuser.io/reframe/
         plugin @reframe/react-kit
         Reframe config ~/ghuser.io/reframe/reframe.config.js
         page configs pages/LandingPage.config.js
                            LogoPage.config.js
                            ProfilePage.config.js

⠦ Building pages (for production)Killed
```

I suspect a t2.nano doesn't have enough RAM for webpack. It would be good to confirm what is going on.

**Comment by brillout** [comment]
I have the same guess.

How about building on your local machine before deploying to production?

**Comment by AurelienLourot** [comment]
yes that's what I have been doing the whole time, building and deploying from my laptop :) But some day I might want to automate and take my laptop out of the process.

**Comment by AurelienLourot** [comment]
Same with t2.micro, fine with t2.small.
-> 2GB RAM needed
