### ISSUE TITLE
I'd like to have my profile on ghuser.io, thanks!

### ISSUE THREAD

**Issue by akshaygulhane** [AurelienLourot/ghuser.io#79]
I'd like to have my profile on ghuser.io, thanks!

I'll be glad to help with any open issues. :)

**Comment by AurelienLourot** [comment]
on it :)

yes it would be awesome if you could help! You can for example pick one of the issues marked as `good first issue`: https://github.com/AurelienLourot/ghuser.io/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

You can find me on [this Discord chat](https://discord.gg/kqXf65G) on the `#ghuser` channel if you have any questions :)

**Comment by AurelienLourot** [comment]
Here you go :) https://ghuser.io/akshaygulhane

It's empty unfortunately because you seem to have never actually pushed any commit to any repo. It might be a bug though (then just point me to a commit you have pushed on GitHub).

**Comment by akshaygulhane** [comment]
@AurelienLourot I think my profile is empty because I don't have any public commits. :(
