### ISSUE TITLE
Profile needed for Naveenaidu26

### ISSUE THREAD

**Issue by Naveenaidu** [AurelienLourot/ghuser.io#82]
I'd like to have my profile on ghuser.io, thanks!

**Comment by AurelienLourot** [comment]
here you go :) https://ghuser.io/Naveenaidu

**Comment by AurelienLourot** [comment]
BTW some of your projects don't show up because they have no stars. Just go give them a star and they will pop up on the next refresh (less than 24 hours), see #22 :)

**Comment by Naveenaidu** [comment]
Thank you :)

**Comment by Naveenaidu** [comment]
Sorry, But it says that the profile does not exist.

**Comment by AurelienLourot** [comment]
I suspect a caching issue. Does it work if you refresh the page?

**Comment by Naveenaidu** [comment]
Yeah! I guess it was the caching issue. Thanks for your time. Really love your project. :)

**Comment by AurelienLourot** [comment]
Thank you :) I have created #84 for the caching issue.
