### ISSUE TITLE
Do you like your profile?

### ISSUE THREAD

**Issue by AurelienLourot** [AurelienLourot/ghuser.io#99]
Hi :)

to make sure we're not wasting resources, I'd like to know if you'd like to keep your profile up and running:

* @aryaminus: https://ghuser.io/aryaminus
* @brandon-rhodes: https://ghuser.io/brandon-rhodes
* @Calinou: https://ghuser.io/Calinou
* @crazy-max: https://ghuser.io/crazy-max
* @geekayush: https://ghuser.io/geekayush
* @itaditya: https://ghuser.io/itaditya
* @jordansissel: https://ghuser.io/jordansissel
* @kunalvishnoi: https://ghuser.io/kunalvishnoi
* @manugarri: https://ghuser.io/manugarri
* @pohka: https://ghuser.io/pohka
* @RichardLitt: https://ghuser.io/RichardLitt
* @rohitdaryanani: https://ghuser.io/rohitdaryanani
* @skywang329: https://ghuser.io/skywang329
* @sw-yx: https://ghuser.io/sw-yx
* @tianshanghong: https://ghuser.io/tianshanghong
* @wilburhimself: https://ghuser.io/wilburhimself

Just give me a quick sign and I won't bother you again. Thanks!

**Comment by itaditya** [comment]
ghuser is really good, I want to keep my site running. Can you please
explain what are the bottlenecks?

**Comment by AurelienLourot** [comment]
Thanks @itaditya :) I'm trying to avoid reaching these limits too soon:

* amount of GitHub API requests per day: refreshing a profile every day requires some amount of API calls.
* DB size: for now the DB is just a set of json files in this repo, which is dirty. At some point it will have to move to a real DB, which will have a cost.
* AWS Lambda free tier: the web app is hosted on AWS Lambda and for now we're still far below the free tier limit.

ghuser is free and it should stay like this as long as possible :) For now the only thing I pay myself is the domain name.

**Comment by RichardLitt** [comment]
Might be easier to just delete all of our profiles; we can re-enable them if we need to. I'm happy going through that process, as I imagine I take a lot of API calls for my profile given the amount of repos.

**Comment by Calinou** [comment]
I like it, keep it running :smiley:

**Comment by manugarri** [comment]
if you guys have limited resources you can remove mine :)

**Comment by jamesgeorge007** [comment]
@AurelienLourot it seems that my profile has been removed. The fact was that I provided ghuser profile link as the personal blog url that would appear on my GitHub profile. So, it would be great if mine was brought back :smiley:

**Comment by AurelienLourot** [comment]
@jamesgeorge007 https://ghuser.io/jamesgeorge007 is working fine, what do you mean?

**Comment by jamesgeorge007** [comment]
@AurelienLourot It's fine right now :+1: 
It was not working as intended a while ago.

**Comment by aryaminus** [comment]
I do like it, but if you are low on resources, you can remove it for now

**Comment by brandon-rhodes** [comment]
You can also remove mine if you're low on resources.

**Comment by itaditya** [comment]
Please keep mine alive

**Comment by tianshanghong** [comment]
If you have limited resources, you can remove mine too. 🤝

**Comment by tianshanghong** [comment]
If you have limited resources, you can remove mine too. 🤝

**Comment by wilburhimself** [comment]
@AurelienLourot I do like it, but if you are low on resources, you can remove it for now ...
